# Generated by Django 3.2.4 on 2021-06-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_number', models.CharField(max_length=64)),
                ('date_of_join', models.CharField(max_length=64)),
                ('annual_vacation', models.IntegerField(choices=[(0, 11), (2, 15), (3, 16), (4, 16), (5, 17), (6, 17), (7, 18), (8, 18)], default=1)),
                ('registration_number', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('work_type', models.CharField(choices=[('정규', '정규 근무'), ('시차', '시차출퇴근')], default='정규', max_length=64)),
                ('salary', models.IntegerField(default=1822480)),
                ('get_in_time', models.TimeField(default='09:00')),
                ('get_off_time', models.TimeField(default='18:00')),
                ('roles', models.ManyToManyField(related_name='users', through='permissions.UserRole', to='permissions.Role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
