# Generated by Django 3.2.4 on 2021-06-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='rights',
        ),
        migrations.RemoveField(
            model_name='roleright',
            name='right',
        ),
        migrations.RemoveField(
            model_name='roleright',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='annual_leave',
        ),
        migrations.AddField(
            model_name='user',
            name='annual_vacation',
            field=models.IntegerField(choices=[(0, 11), (2, 15), (3, 16), (4, 16), (5, 17), (6, 17), (7, 18), (8, 18)], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='get_in_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='user',
            name='get_off_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.IntegerField(default=1822480),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_join',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='permissions.UserRole', to='permissions.Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_type',
            field=models.CharField(choices=[('정규', '정규 근무'), ('시차', '시차출퇴근')], default='정규', max_length=64),
        ),
        migrations.DeleteModel(
            name='Right',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleRight',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
