# Generated by Django 3.2.4 on 2021-06-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual', models.IntegerField()),
                ('leave_count', models.IntegerField()),
            ],
            options={
                'db_table': 'annual_leaves',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_join',
            field=models.DateField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='annual_vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.annualleave'),
        ),
    ]
