# Generated by Django 3.2.4 on 2021-06-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_remaining_annual_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
