# Generated by Django 3.2.4 on 2021-06-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
