# Generated by Django 3.2.4 on 2021-06-11 05:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '출근 전'), (2, '출근'), (3, '지각'), (4, '결석'), (5, '퇴근'), (6, '야근'), (7, '휴일근무')], default=1)),
                ('start_at', models.DateTimeField(default=datetime.datetime(2021, 6, 11, 5, 47, 41, 15048, tzinfo=utc))),
                ('end_at', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, '신청'), (2, '결재'), (3, '반려')], default=1)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('연차', 1), ('공가', 0), ('경조', 0)], default='연차', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaves',
            },
        ),
    ]
