# Generated by Django 3.2.4 on 2021-06-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('유급휴가', 8), ('무급휴가', 0), ('정상근무', 8)], default='정상근무', max_length=64),
        ),
    ]
