# Generated by Django 3.2.4 on 2021-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_rename_type_schedule_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
