# Generated by Django 3.2.4 on 2021-06-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_schedule_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
