# Generated by Django 3.2.4 on 2021-06-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20210616_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='get_in_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='get_off_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
