# Generated by Django 3.2.4 on 2021-06-14 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('draft_at', models.DateField()),
                ('start_at', models.DateField(default=None, null=True)),
                ('end_at', models.DateField(default=None, null=True)),
                ('approval_at', models.DateField(default=None, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'drafts',
            },
        ),
        migrations.CreateModel(
            name='DraftApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.draft')),
            ],
            options={
                'db_table': 'drafts_approvers',
            },
        ),
        migrations.AddField(
            model_name='draft',
            name='approvers',
            field=models.ManyToManyField(related_name='drafts', through='drafts.DraftApprover', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='draft',
            name='drafter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
