# Generated by Django 3.2.4 on 2021-06-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='approvers',
        ),
        migrations.AlterField(
            model_name='draft',
            name='type',
            field=models.CharField(choices=[('연차', 1), ('반차', 0.5), ('공가', 0), ('경조', 0)], max_length=64),
        ),
    ]
