# Generated by Django 3.2.4 on 2021-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0003_auto_20210629_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
